---

- name: Deploy counter64.io
  hosts: tag_Role_app
  become: yes
  tasks:
    - name: Provision docker and docker-compose
      include_role:
        name: docker

    - name: Put docker-compose to the app server
      copy:
        src: ../docker-compose.yml
        dest: /app/  # trailing slash will create the dir

    - name: Launch app via docker-compose
      docker_compose:
        project_src: /app
